version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            docker build -t api .
      - run:
          name: run tests
          command: |
            docker run -it api /app/entrypoint.tests.sh